<?php

namespace app\home\controller;

use think\Lang;
/**
 * ============================================================================
 * DSMall多用户商城
 * ============================================================================
 * 版权所有 2014-2028 长沙德尚网络科技有限公司，并保留所有权利。
 * 网站地址: http://www.csdeshang.com
 * ----------------------------------------------------------------------------
 * 这不是一个自由软件！您只能在不用于商业目的的前提下对程序代码进行修改和使用 .
 * 不允许对程序代码以任何形式任何目的的再发布。
 * ============================================================================
 * 服务机构消息控制器
 */
class FuwuManageNotice extends BaseFuwu
{

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        Lang::load(APP_PATH . 'api/lang/' . config('default_lang') . '/fuwu_manage_notice.lang.php');
    }

    public function index()
    {
        $o2o_fuwu_notice_model = model('o2o_fuwu_notice');
        $conditions = array('o2o_fuwu_account_id' => $this->o2o_fuwu_organization_info['o2o_fuwu_account_id']);

        $notice_list = $o2o_fuwu_notice_model->getO2oFuwuNoticeList($conditions, 20);
        $notice_ids = array();
        foreach ($notice_list as $key => $val) {
            $notice_ids[] = $val['o2o_fuwu_notice_id'];
        }
        if (!empty($notice_ids)) {
            $o2o_fuwu_notice_model->editO2oFuwuNotice(array('o2o_fuwu_notice_read' => 1), array('o2o_fuwu_notice_id' => array('in', $notice_ids)));
        }

        $this->assign('notice_list', $notice_list);
        $this->assign('show_page', $o2o_fuwu_notice_model->page_info->render());
        $this->setFuwuCurMenu('fuwu_manage_notice');
        $this->setFuwuCurItem('index');
        return $this->fetch($this->template_dir . 'index');
    }
    /**
     * 导航
     *
     * @param string $menu_type 导航类型
     * @param string $menu_key 当前导航的menu_key
     * @return
     */
    protected function getFuwuItemList() {
        $menu_array = array(
            array(
                'name' => 'index', 'text' => '消息列表',
                'url' => url('FuwuManageNotice/index')
            ),
        );

        
        return $menu_array;
    }
}
