<?php
return array (
  'dplayer' => 
  array (
    'status' => '1',
    'from' => 'dplayer',
    'show' => 'DPlayer-H5播放器',
    'des' => 'dplayer.js.org',
    'target' => '_self',
    'ps' => '1',
    'parse' => '',
    'sort' => '908',
    'tip' => '无需安装任何插件',
    'id' => 'dplayer',
  ),
  'videojs' => 
  array (
    'status' => '1',
    'sort' => '907',
    'from' => 'videojs',
    'show' => 'videojs-H5播放器',
    'des' => 'videojs.com',
    'parse' => '',
    'ps' => '0',
    'tip' => '无需安装任何插件',
    'id' => 'videojs',
  ),
  'iva' => 
  array (
    'status' => '1',
    'from' => 'iva',
    'show' => 'iva-H5播放器',
    'des' => 'videojj.com',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '906',
    'tip' => '无需安装任何插件',
    'id' => 'iva',
  ),
  'iframe' => 
  array (
    'status' => '1',
    'from' => 'iframe',
    'show' => 'iframe外链数据',
    'des' => 'iframe外链数据',
    'ps' => '0',
    'parse' => '',
    'sort' => '905',
    'tip' => '无需安装任何插件',
    'id' => 'iframe',
  ),
  'link' => 
  array (
    'status' => '1',
    'sort' => '904',
    'from' => 'link',
    'show' => '外链数据',
    'des' => '外部网站播放链接',
    'ps' => '0',
    'parse' => '',
    'tip' => '无需安装任何插件',
    'id' => 'link',
  ),
  'swf' => 
  array (
    'status' => '1',
    'sort' => '903',
    'from' => 'swf',
    'show' => 'Flash文件',
    'des' => 'swf',
    'parse' => '',
    'ps' => '0',
    'tip' => '无需安装任何插件',
    'id' => 'swf',
  ),
  'flv' => 
  array (
    'status' => '1',
    'from' => 'flv',
    'show' => 'Flv文件',
    'des' => 'flv',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '902',
    'tip' => '无需安装任何插件	',
    'id' => 'flv',
  ),
  'youku' => 
  array (
    'status' => '1',
    'from' => 'youku',
    'show' => '优酷视频',
    'des' => 'youku.com',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://jx.yparse.com/index.php?url=',
    'sort' => '618',
    'tip' => '无需安装任何插件',
    'id' => 'youku',
  ),
  '56_' => 
  array (
    'status' => '1',
    'from' => '56_',
    'show' => '我乐视频',
    'des' => '56.com',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://jx.yparse.com/index.php?url=',
    'sort' => '617',
    'tip' => '无需安装任何插件',
    'id' => '56_',
  ),
  'tudou' => 
  array (
    'status' => '1',
    'from' => 'tudou',
    'show' => '土豆视频',
    'des' => 'tudou.com',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://jx.yparse.com/index.php?url=',
    'sort' => '616',
    'tip' => '无需安装任何插件',
    'id' => 'tudou',
  ),
  'ku6' => 
  array (
    'status' => '1',
    'from' => 'ku6',
    'show' => '酷6视频',
    'des' => 'ku6.com',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://jx.yparse.com/index.php?url=',
    'sort' => '615',
    'tip' => '无需安装任何插件',
    'id' => 'ku6',
  ),
  'qq' => 
  array (
    'status' => '1',
    'from' => 'qq',
    'show' => '腾讯视频',
    'des' => 'v.qq.com',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://jx.yparse.com/index.php?url=',
    'sort' => '614',
    'tip' => '无需安装任何插件',
    'id' => 'qq',
  ),
  'sohu' => 
  array (
    'status' => '1',
    'from' => 'sohu',
    'show' => '搜狐视频',
    'des' => 'v.sohu.com',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://jx.yparse.com/index.php?url=',
    'sort' => '613',
    'tip' => '无需安装任何插件',
    'id' => 'sohu',
  ),
  'qiyi' => 
  array (
    'status' => '1',
    'from' => 'qiyi',
    'show' => '奇艺视频',
    'des' => 'qiyi.com',
    'target' => '_self',
    'ps' => '0',
    'parse' => 'https://jx.yparse.com/index.php?url=',
    'sort' => '611',
    'tip' => '无需安装任何插件',
    'id' => 'qiyi',
  ),
  'letv' => 
  array (
    'status' => '1',
    'from' => 'letv',
    'show' => '乐视视频',
    'des' => 'letv.com',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://jx.yparse.com/index.php?url=',
    'sort' => '610',
    'tip' => '无需安装任何插件',
    'id' => 'letv',
  ),
  'funshion' => 
  array (
    'status' => '1',
    'from' => 'funshion',
    'show' => '风行视频',
    'des' => 'funshion.com',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://jx.yparse.com/index.php?url=',
    'sort' => '609',
    'tip' => '无需安装任何插件',
    'id' => 'funshion',
  ),
  'mgtv' => 
  array (
    'status' => '1',
    'from' => 'mgtv',
    'show' => '芒果tv',
    'des' => 'mgtv.com',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://jx.yparse.com/index.php?url=',
    'sort' => '608',
    'tip' => '无需安装任何插件',
    'id' => 'mgtv',
  ),
  'wasu' => 
  array (
    'status' => '1',
    'from' => 'wasu',
    'show' => '华数tv',
    'des' => 'wasu.cn',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://jx.yparse.com/index.php?url=',
    'sort' => '607',
    'tip' => '无需安装任何插件',
    'id' => 'wasu',
  ),
  'pptv' => 
  array (
    'status' => '1',
    'from' => 'pptv',
    'show' => 'pptv',
    'des' => 'pptv.com',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://jx.yparse.com/index.php?url=',
    'sort' => '602',
    'tip' => '无需安装任何插件',
    'id' => 'pptv',
  ),
  'm3u8' => 
  array (
    'status' => '1',
    'from' => 'm3u8',
    'show' => ' 步步高资源M3U8播放器',
    'des' => 'http://www.bbkdj.com/help/maccms.html',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://jx.yparse.com/index.php?url=',
    'sort' => '2',
    'tip' => '无需播放器，在线播放',
    'id' => 'm3u8',
  ),
  'bbkdj' => 
  array (
    'status' => '1',
    'from' => 'bbkdj',
    'show' => '步步高云播放器',
    'des' => 'http://www.bbkdj.com/help/maccms.html',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://jx.yparse.com/index.php?url=',
    'sort' => '1',
    'tip' => '无需播放器，在线播放',
    'id' => 'bbkdj',
  ),
  'kkm3u8' => 
  array (
    'status' => '1',
    'from' => 'kkm3u8',
    'show' => '酷云m3u8',
    'des' => 'http://www.kuyunzy.cc',
    'ps' => '1',
    'parse' => 'https://www.kuyunjiexi.com/?url=',
    'sort' => '99',
    'tip' => '在线播放,无需安装播放器',
    'id' => 'kkm3u8',
  ),
);